print wheel file path

diff --git a/.github/workflows/pull-request-management.yml b/.github/workflows/pull-request-management.yml
--- a/.github/workflows/pull-request-management.yml
+++ b/.github/workflows/pull-request-management.yml
@@ -509,17 +509,21 @@ jobs:
         run: |
           pip install "ansible-core<2.19.0" -r .github/requirements-ci.txt --upgrade
 
-      - name: Find and print wheel file path
-        shell: bash
+      # - name: Find and print wheel file path
+      #   shell: bash
+      #   run: |
+      #     set -e
+      #     echo "Searching for the wheel file..."
+      #     FILE_PATH=$(find . -type f -name '*5.2.0.dev1-py3-none-any.whl')
+      #     if [ -z "$FILE_PATH" ]; then
+      #       echo "Error: Wheel file not found."
+      #       exit 1
+      #     fi
+      #     echo "Found wheel file at: $FILE_PATH"
+      
+      - name: list
         run: |
-          set -e
-          echo "Searching for the wheel file..."
-          FILE_PATH=$(find . -type f -name '*5.2.0.dev1-py3-none-any.whl')
-          if [ -z "$FILE_PATH" ]; then
-            echo "Error: Wheel file not found."
-            exit 1
-          fi
-          echo "Found wheel file at: $FILE_PATH"
+          ls -l /home/runner/.cache/pip/wheels/3f/b8/e4/06a7ef48f65a79014cac4474ca06ed03f987ae6daa2aa02141/
 
       - name: 'Run ansible-test sanity'
         run: |
